# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-38c120ba-c30a-48c3-93fd-40e8c26769e4";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-38c120ba-c30a-48c3-93fd-40e8c26769e4".device = "/dev/disk/by-uuid/38c120ba-c30a-48c3-93fd-40e8c26769e4";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0A62-6B6D";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/f39a150a-a3f6-44b0-ac81-888294e33f9c";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
