#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "missing the session name!" >&2
fi

session_name="$1"
current_session=""

if [ -n "$TMUX" ]; then
  current_session=$(tmux display-message -p '#S')
fi

if ! tmux has-session -t "$session_name" 2>/dev/null; then
  tmux new-session -d -s "$session_name"
fi
if [ "$current_session" != "$session_name" ]; then
  if [ -z "$TMUX" ]; then
    tmux attach-session -t "$session_name"
  else
    tmux switch-client -t "$session_name"
  fi
else
  echo "Already on ${session_name} session"
fi
