# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ehci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7db20087-1f20-4109-a91e-59c9d1032ac7";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7db20087-1f20-4109-a91e-59c9d1032ac7".device = "/dev/disk/by-uuid/7db20087-1f20-4109-a91e-59c9d1032ac7";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A0BB-833F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-49d2d068-28eb-4625-8f0e-26bb8d4ad65c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
