[bar.default]
position = "left"
thickness = 48
start = [
  "launcher",
  "wallpaper",
  "clock",
]

center = [
  "workspaces",
]

end = [
  "volume",
  "brightness",
  "media",
  "network",
  "bluetooth",
  "battery",
  "notifications",
  "tray",
  "control-center",
]
widget_spacing = 12
margin_ends = 0
margin_edge = 0

[widget.volume]
show_label = false

[widget.brightness]
show_label = false

[widget.battery]
show_label = false

[widget.network]
show_label = false
show_vpn_label = false

[widget.taskbar]
scale = 3
# type = "taskbar"
# icon_scale = 2

[location]
# auto_locate = true
auto_locate = false
address = "Piekary Śląskie, Poland"
